project_id = "oolqwypnmoxcvesaeefx"

[functions.recommend]
verify_jwt = false

[functions.unsplash-image]
verify_jwt = false

[functions.scan-ingredients]
verify_jwt = false

[functions.ingredients-to-recipes]
verify_jwt = false